### ISSUE TITLE
Login.gov authenication is broken

### ISSUE THREAD

**Issue by lauraGgit** [nciinc/fs-permit-platform#698]
https://fs-intake-api-trees.app.cloud.gov/auth/login-gov/openid/login

Trackback:
```
Error: Unknown authentication strategy "oidc"
    at attempt (/home/vcap/app/node_modules/passport/lib/middleware/authenticate.js:186:37)
    at authenticate (/home/vcap/app/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vcap/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/vcap/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at /home/vcap/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/vcap/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/vcap/app/node_modules/express/lib/router/index.js:174:3)
    at router (/home/vcap/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vcap/app/node_modules/express/lib/router/index.js:317:13)
    at /home/vcap/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/vcap/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/vcap/app/node_modules/passport/lib/middleware/authenticate.js:338:9)
    at SessionStrategy.authenticate (/home/vcap/app/node_modules/passport/lib/strategies/session.js:75:10)
    at attempt (/home/vcap/app/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/home/vcap/app/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vcap/app/node_modules/express/lib/router/index.js:317:13)
    at /home/vcap/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:335:12)
    at next (/home/vcap/app/node_modules/express/lib/router/index.js:275:10)
    at initialize (/home/vcap/app/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/vcap/app/node_modules/express/lib/router/index.js:317:13)
```

**Comment by lauraGgit** [comment]
Configuration error with login dev environment closing, so archiving
